interface ProductFilter {
	[key: string]: {
		material?: { value: string; label: string }[];
		color?: { value: string; label: string }[];
		shape?: { value: string; label: string }[];
		style?: { value: string; label: string }[];
		finish?: { value: string; label: string }[];
		size?: { value: string; label: string }[];
		texture?: { value: string; label: string }[];
		backing?: { value: string; label: string }[];
	};
}

export const productFilter: ProductFilter = {
	tile: {
		material: [
			{ value: "porcelain", label: "Porcelain" },
			{ value: "ceramic", label: "Ceramic" },
		],
		color: [
			{ value: "gray", label: "Gray" },
			{ value: "white", label: "White" },
			{ value: "blue", label: "Blue" },
			{ value: "beige", label: "Beige" },
			{ value: "green", label: "Green" },
			{ value: "black", label: "Black" },
			{ value: "brown", label: "Brown" },
			{ value: "cream", label: "Cream" },
			{ value: "gold", label: "Gold" },
			{ value: "multi", label: "Multi" },
			{ value: "orange", label: "Orange" },
			{ value: "purple", label: "Purple" },
			{ value: "red", label: "Red" },
			{ value: "silver", label: "Silver" },
			{ value: "taupe", label: "Taupe" },
			{ value: "yellow", label: "Yellow" },
		],
		shape: [
			{ value: "rectangle", label: "Rectangle" },
			{ value: "square", label: "Square" },
			{ value: "arabesque", label: "Arabesque" },
			{ value: "hexagon", label: "Hexagon" },
			{ value: "liner", label: "Liner" },
			{ value: "pencilLiner", label: "Pencil Liner" },
			{ value: "picket", label: "Picket" },
		],
		finish: [
			{ value: "glass", label: "Glass" },
			{ value: "glossy", label: "Glossy" },
			{ value: "matte", label: "Matte" },
			{ value: "polished", label: "Polished" },
			{ value: "satin", label: "Satin" },
			{ value: "textured", label: "Textured" },
		],
		size: [
			{ value: "extraLarge", label: "Extra Large" },
			{ value: "large", label: "Large" },
			{ value: "medium", label: "Medium" },
			{ value: "small", label: "Small" },
			{ value: "various", label: "Various" },
		],
	},
	cabinets: {
		material: [
			{ value: "wood", label: "Wood" },
			{ value: "alder", label: "Alder" },
			{ value: "cherry", label: "Cherry" },
			{ value: "duraform", label: "Duraform" },
			{ value: "hardwood", label: "Hardwood" },
			{ value: "hdf", label: "HDF" },
			{ value: "hickory", label: "Hickory" },
			{ value: "highGlossLaminate", label: "High Gloss Laminate" },
			{ value: "knottyAlder", label: "Knotty Alder" },
			{ value: "maple", label: "Maple" },
			{ value: "matteLaminate", label: "Matte Laminate" },
			{ value: "mdf", label: "MDF" },
			{ value: "oak", label: "Oak" },
			{ value: "painted", label: "Painted" },
			{ value: "pet", label: "PET" },
			{
				value: "prefinishedWoodVeneer",
				label: "Prefinished Wood Veneer",
			},
			{ value: "quarterSawnOak", label: "Quarter Sawn Oak" },
			{ value: "redOak", label: "Red Oak" },
			{ value: "riftWhiteOak", label: "Rift White Oak" },
			{ value: "rusticMaple", label: "Rustic Maple" },
			{ value: "sapele", label: "Sapele" },
			{ value: "softTouchLaminate", label: "Soft Touch Laminate" },
			{ value: "texturedLaminate", label: "Textured Laminate" },
			{ value: "thermofoil", label: "Thermofoil" },
			{ value: "walnut", label: "Walnut" },
			{ value: "wood", label: "Wood" },
		],
		style: [
			{ value: "shaker", label: "Shaker" },
			{ value: "contemporary", label: "Contemporary" },
			{ value: "traditional", label: "Traditional" },
			{ value: "transitional", label: "Transitional" },
		],
		color: [{ value: "white", label: "White" }],
	},
	carpet: {
		color: [
			{ value: "beige", label: "Beige" },
			{ value: "blue", label: "Blue" },
			{ value: "brown", label: "Brown" },
			{ value: "gold", label: "Gold" },
			{ value: "gray", label: "Gray" },
			{ value: "green", label: "Green" },
			{ value: "orange", label: "Orange" },
			{ value: "red", label: "Red" },
			{ value: "violet", label: "Violet" },
		],
		texture: [
			{ value: "pattern", label: "Pattern" },
			{ value: "loop", label: "Loop" },
			{ value: "texture", label: "Texture" },
			{ value: "twist", label: "Twist" },
		],
		material: [
			{ value: "nylon", label: "Nylon" },
			{ value: "polyester", label: "Polyester" },
			{ value: "ansoHighPerformance", label: "ANSO High-Performance" },
			{ value: "wool", label: "Wool" },
		],
		backing: [
			{ value: "classicBac", label: "ClassicBac" },
			{ value: "softBac", label: "SoftBac" },
			{ value: "lifeGuard", label: "LifeGuard" },
		],
	},
	hardwood: {
		color: [
			{ value: "brown", label: "Brown" },
			{ value: "gold", label: "Gold" },
			{ value: "gray", label: "Gray" },
			{ value: "red", label: "Red" },
			{ value: "white", label: "White" },
			{ value: "blonde", label: "Blonde" },
		],
		material: [
			{ value: "nylon", label: "Nylon" },
			{ value: "polyester", label: "Polyester" },
			{ value: "ansoHighPerformance", label: "ANSO High-Performance" },
			{ value: "wool", label: "Wool" },
		],
	},
	decking: {
		material: [
			{ value: "wood", label: "Wood" },
			{ value: "alder", label: "Alder" },
			{ value: "cherry", label: "Cherry" },
			{ value: "duraform", label: "Duraform" },
			{ value: "hardwood", label: "Hardwood" },
			{ value: "hdf", label: "HDF" },
			{ value: "hickory", label: "Hickory" },
			{ value: "highGlossLaminate", label: "High Gloss Laminate" },
			{ value: "knottyAlder", label: "Knotty Alder" },
			{ value: "maple", label: "Maple" },
			{ value: "matteLaminate", label: "Matte Laminate" },
			{ value: "mdf", label: "MDF" },
			{ value: "oak", label: "Oak" },
			{ value: "painted", label: "Painted" },
			{ value: "pet", label: "PET" },
			{
				value: "prefinishedWoodVeneer",
				label: "Prefinished Wood Veneer",
			},
			{ value: "quarterSawnOak", label: "Quarter Sawn Oak" },
			{ value: "redOak", label: "Red Oak" },
			{ value: "riftWhiteOak", label: "Rift White Oak" },
			{ value: "rusticMaple", label: "Rustic Maple" },
			{ value: "sapele", label: "Sapele" },
			{ value: "softTouchLaminate", label: "Soft Touch Laminate" },
			{ value: "texturedLaminate", label: "Textured Laminate" },
			{ value: "thermofoil", label: "Thermofoil" },
			{ value: "walnut", label: "Walnut" },
			{ value: "wood", label: "Wood" },
		],
		style: [
			{ value: "shaker", label: "Shaker" },
			{ value: "contemporary", label: "Contemporary" },
			{ value: "traditional", label: "Traditional" },
			{ value: "transitional", label: "Transitional" },
		],
		color: [{ value: "white", label: "White" }],
	},
	doors: {
		material: [
			{ value: "wood", label: "Wood" },
			{ value: "alder", label: "Alder" },
			{ value: "cherry", label: "Cherry" },
			{ value: "duraform", label: "Duraform" },
			{ value: "hardwood", label: "Hardwood" },
			{ value: "hdf", label: "HDF" },
			{ value: "hickory", label: "Hickory" },
			{ value: "highGlossLaminate", label: "High Gloss Laminate" },
			{ value: "knottyAlder", label: "Knotty Alder" },
			{ value: "maple", label: "Maple" },
			{ value: "matteLaminate", label: "Matte Laminate" },
			{ value: "mdf", label: "MDF" },
			{ value: "oak", label: "Oak" },
			{ value: "painted", label: "Painted" },
			{ value: "pet", label: "PET" },
			{
				value: "prefinishedWoodVeneer",
				label: "Prefinished Wood Veneer",
			},
			{ value: "quarterSawnOak", label: "Quarter Sawn Oak" },
			{ value: "redOak", label: "Red Oak" },
			{ value: "riftWhiteOak", label: "Rift White Oak" },
			{ value: "rusticMaple", label: "Rustic Maple" },
			{ value: "sapele", label: "Sapele" },
			{ value: "softTouchLaminate", label: "Soft Touch Laminate" },
			{ value: "texturedLaminate", label: "Textured Laminate" },
			{ value: "thermofoil", label: "Thermofoil" },
			{ value: "walnut", label: "Walnut" },
			{ value: "wood", label: "Wood" },
		],
		style: [
			{ value: "shaker", label: "Shaker" },
			{ value: "contemporary", label: "Contemporary" },
			{ value: "traditional", label: "Traditional" },
			{ value: "transitional", label: "Transitional" },
		],
		color: [{ value: "white", label: "White" }],
	},
	windows: {
		material: [
			{ value: "wood", label: "Wood" },
			{ value: "alder", label: "Alder" },
			{ value: "cherry", label: "Cherry" },
			{ value: "duraform", label: "Duraform" },
			{ value: "hardwood", label: "Hardwood" },
			{ value: "hdf", label: "HDF" },
			{ value: "hickory", label: "Hickory" },
			{ value: "highGlossLaminate", label: "High Gloss Laminate" },
			{ value: "knottyAlder", label: "Knotty Alder" },
			{ value: "maple", label: "Maple" },
			{ value: "matteLaminate", label: "Matte Laminate" },
			{ value: "mdf", label: "MDF" },
			{ value: "oak", label: "Oak" },
			{ value: "painted", label: "Painted" },
			{ value: "pet", label: "PET" },
			{
				value: "prefinishedWoodVeneer",
				label: "Prefinished Wood Veneer",
			},
			{ value: "quarterSawnOak", label: "Quarter Sawn Oak" },
			{ value: "redOak", label: "Red Oak" },
			{ value: "riftWhiteOak", label: "Rift White Oak" },
			{ value: "rusticMaple", label: "Rustic Maple" },
			{ value: "sapele", label: "Sapele" },
			{ value: "softTouchLaminate", label: "Soft Touch Laminate" },
			{ value: "texturedLaminate", label: "Textured Laminate" },
			{ value: "thermofoil", label: "Thermofoil" },
			{ value: "walnut", label: "Walnut" },
			{ value: "wood", label: "Wood" },
		],
		style: [
			{ value: "shaker", label: "Shaker" },
			{ value: "contemporary", label: "Contemporary" },
			{ value: "traditional", label: "Traditional" },
			{ value: "transitional", label: "Transitional" },
		],
		color: [{ value: "white", label: "White" }],
	},
	countertops: {
		material: [
			{ value: "wood", label: "Wood" },
			{ value: "alder", label: "Alder" },
			{ value: "cherry", label: "Cherry" },
			{ value: "duraform", label: "Duraform" },
			{ value: "hardwood", label: "Hardwood" },
			{ value: "hdf", label: "HDF" },
			{ value: "hickory", label: "Hickory" },
			{ value: "highGlossLaminate", label: "High Gloss Laminate" },
			{ value: "knottyAlder", label: "Knotty Alder" },
			{ value: "maple", label: "Maple" },
			{ value: "matteLaminate", label: "Matte Laminate" },
			{ value: "mdf", label: "MDF" },
			{ value: "oak", label: "Oak" },
			{ value: "painted", label: "Painted" },
			{ value: "pet", label: "PET" },
			{
				value: "prefinishedWoodVeneer",
				label: "Prefinished Wood Veneer",
			},
			{ value: "quarterSawnOak", label: "Quarter Sawn Oak" },
			{ value: "redOak", label: "Red Oak" },
			{ value: "riftWhiteOak", label: "Rift White Oak" },
			{ value: "rusticMaple", label: "Rustic Maple" },
			{ value: "sapele", label: "Sapele" },
			{ value: "softTouchLaminate", label: "Soft Touch Laminate" },
			{ value: "texturedLaminate", label: "Textured Laminate" },
			{ value: "thermofoil", label: "Thermofoil" },
			{ value: "walnut", label: "Walnut" },
			{ value: "wood", label: "Wood" },
		],
		style: [
			{ value: "shaker", label: "Shaker" },
			{ value: "contemporary", label: "Contemporary" },
			{ value: "traditional", label: "Traditional" },
			{ value: "transitional", label: "Transitional" },
		],
		color: [{ value: "white", label: "White" }],
	},
};
