export const locationsList = {
	wa: [
		{ location: "Seattle", link: "/location/seattle" },
		{ location: "Spokane", link: "/location/spokane" },
		{ location: "Vancouver", link: "/location/vancouver" },
		{ location: "Bellevue", link: "/location/bellevue" },
		{ location: "Renton", link: "/location/renton" },
		{ location: "Federal Way", link: "/location/federal-way" },
		{ location: "Kirkland", link: "/location/kirkland" },
		{ location: "Yakima", link: "/location/yakima" },
		{ location: "Nanaimo", link: "/location/nanaimo" },
		{ location: "Kennewick", link: "/location/kennewick" },
		{ location: "Auburn", link: "/location/auburn" },
		{ location: "Pasco", link: "/location/pasco" },
		{ location: "Redmond", link: "/location/redmond" },
		{ location: "Sammamish", link: "/location/sammamish" },
		{ location: "Richland", link: "/location/richland" },
		{ location: "Shoreline", link: "/location/shoreline" },
		{ location: "Olympia", link: "/location/olympia" },
		{ location: "Lacey", link: "/location/lacey" },
		{ location: "Bothell", link: "/location/bothell" },
		{ location: "Puyallup", link: "/location/puyallup" },
		{ location: "Edmonds", link: "/location/edmonds" },
		{ location: "Issaquah", link: "/location/issaquah" },
		{ location: "Lynnwood", link: "/location/lynnwood" },
		{ location: "Wenatchee", link: "/location/wenatchee" },
		{ location: "Lake Stevens", link: "/location/lake-stevens" },
		{ location: "University Place", link: "/location/university-place" },
		{ location: "Walla Walla", link: "/location/walla-walla" },
		{ location: "Maple Valley", link: "/location/maple-valley" },
		{ location: "Mercer Island", link: "/location/mercer-island" },
		{ location: "Bainbridge Island", link: "/location/bainbridge-island" },
		{ location: "Kenmore", link: "/location/kenmore" },
		{ location: "Mukilteo", link: "/location/mukilteo" },
		{ location: "Mountlake Terrace", link: "/location/mountlake-terrace" },
		{ location: "Bonney Lake", link: "/location/bonney-lake" },
		{ location: "Ellensburg", link: "/location/ellensburg" },
		{ location: "Mill Creek", link: "/location/mill-creek" },
		{ location: "Covington", link: "/location/covington" },
		{ location: "Anacortes", link: "/location/anacortes" },
		{ location: "Camano Island", link: "/location/camano-island" },
		{ location: "Lake Forest Park", link: "/location/lake-forest-park" },
		{ location: "Snoqualmie", link: "/location/snoqualmie" },
		{ location: "Newcastle", link: "/location/newcastle" },
		{ location: "Sumner", link: "/location/sumner" },
		{ location: "Normandy Park", link: "/location/normandy-park" },
		{ location: "Des Moines", link: "/location/des-moines" },
		{ location: "Medina", link: "/location/medina" },
		{ location: "Clyde Hill", link: "/location/clyde-hill" },
		{ location: "Woodway", link: "/location/woodway" },
		{ location: "Yarrow Point", link: "/location/yarrow-point" },
		{ location: "Hunts Point", link: "/location/hunts-point" },
		{
			location: "Beaux Arts Village",
			link: "/location/beaux-arts-village",
		},
	],
	bc: [
		{ location: "Victoria", link: "/location/victoria" },
		{ location: "Saanich", link: "/location/saanich" },
		{ location: "Oak Bay", link: "/location/oak-bay" },
		{ location: "Esquimalt", link: "/location/esquimalt" },
		{ location: "View Royal", link: "/location/view-royal" },
		{ location: "Colwood", link: "/location/colwood" },
		{ location: "Langford", link: "/location/langford" },
		{ location: "Metchosin", link: "/location/metchosin" },
		{ location: "Highlands", link: "/location/highlands" },
		{ location: "Sooke", link: "/location/sooke" },
		{ location: "Central Saanich", link: "/location/central-saanich" },
		{ location: "North Saanich", link: "/location/north-saanich" },
		{ location: "Sidney", link: "/location/sidney" },
	],
};
